#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Docopt\Handler as Docopt;

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)

Options:
  -h --help     Show this screen
  -v --version  Show version
DOC;

$args = (new Docopt())->handle($doc, ['version' => '1.0.0']);

print_r($args);